// Shared data types. No Obsidian imports, so everything here is unit-testable.

import type { Cost } from "./cost";

export type Difficulty = "easy" | "medium" | "hard";
export const DIFFICULTIES: Difficulty[] = ["easy", "medium", "hard"];
export const POINTS_PER_DIFFICULTY: Record<Difficulty, number> = { easy: 1, medium: 2, hard: 3 };

/** Self-rated confidence per answer. Only used for calibration, never for scheduling. */
export type Confidence = "guessed" | "unsure" | "sure";
export const CONFIDENCE_LEVELS: Confidence[] = ["guessed", "unsure", "sure"];

export type QuestionType = "mc" | "open";

/** Difficulty level chosen when creating a quiz. */
export type Level = "intro" | "normal" | "exam";

/** Which question types a quiz may contain. */
export type QuestionTypes = "mixed" | "mc" | "open";

export const ERROR_TYPES = ["knowledge_gap", "confusion", "incomplete", "application", "calculation", "imprecise"] as const;
export type ErrorType = (typeof ERROR_TYPES)[number];

/** A question as generated by the AI, including the solution the learner does not see. */
export interface Question {
	nr: number;
	type: QuestionType;
	difficulty: Difficulty;
	topic: string;
	question: string;
	/** MC only */
	options: string[];
	/** MC only: index of the correct option */
	correct: number | null;
	/** Model answer (MC: explanation) */
	solution: string;
	/** Where in the source this is covered, e.g. "page 17" */
	reference: string;
}

/** Everything stored (hidden) inside a quiz note. */
export interface QuizData {
	id: string;
	title: string;
	/** Vault path of the source file or folder */
	source: string;
	/** Page range, e.g. "12-30", or "" */
	pages: string;
	/** ISO timestamp, minutes precision */
	created: string;
	questions: Question[];
	result?: Result;
	/** Answers at the time of evaluation */
	answers?: Answer[];
	/** Token usage and estimated cost (create + evaluate) */
	cost?: Cost;
	/** Path of the past exam used as style template */
	styleTemplate?: string;
	level?: Level;
}

/** The learner's answer, read back from the Markdown note. */
export interface Answer {
	nr: number;
	/** MC: indices of the checked options */
	checked: number[];
	/** Open: written text */
	text: string;
	confidence?: Confidence | null;
}

/** Evaluation of one question. */
export interface Evaluation {
	nr: number;
	points: number;
	max: number;
	/** null when full marks */
	errorType: ErrorType | null;
	whatWasWrong: string;
	correct: string;
	reference: string;
	followUp: string;
	confidence?: Confidence | null;
}

export interface TopicScore {
	topic: string;
	points: number;
	max: number;
	percent: number;
}

export interface Result {
	/** ISO timestamp (UTC, minutes precision) */
	evaluated: string;
	points: number;
	max: number;
	percent: number;
	evaluations: Evaluation[];
	topics: TopicScore[];
	errorTypes: Partial<Record<ErrorType, number>>;
	summary: string;
}
